version: '3'

services:
  awsfileupload:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  awsfiledownload:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

